FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --quiet && \
    apt-get install --quiet --yes \
    software-properties-common \
    openssh-client \
    git \
    fish \
    vim \
    curl

# Shell
ENTRYPOINT [ "/usr/bin/fish" ]